# Values related to the detection the image
WIDTH = 640
HEIGHT = 480

FEATURES_FILTER_MIN_ASPECT_RATIO = 0.75
FEATURES_FILTER_MIN_AREA = 900
FEATURES_FILTER_MAX_AREA = 20000
FEATURES_FILTER_SOLIDITY = 0.9
FEATURES_FILTER_POSITIONAL_2_DISTANCE  = 1.25
FEATURES_POLY_APPROX_DEFAULT_EPSILON = 10

FILTER_GAUSSIAN_DEFAULT_KSIZE = 7
FILTER_MORPHOLOGICAL_DEFAULT_KSIZE = 3
FILTER_ADAPTIVE_THRESHOLD_BLOCK_SIZE = 45
FILTER_ADAPTIVE_THRESHOLD_CONSTANT = 2

ORIENTATION_ESTIMATED_FOV_W = 60
ORIENTATION_ESTIMATED_FOV_H = 47.5
